# Generated by Django 3.1 on 2020-09-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_lista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='lista',
        ),
    ]
