# Generated by Django 3.1 on 2020-09-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_remove_todo_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='lista',
            field=models.TextField(default='lista'),
        ),
    ]
