# Generated by Django 3.1 on 2020-09-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_todolistitem_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
